// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbvrktldfvpjxgcwwztn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5idnJrdGxkZnZwanhnY3d3enRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDk1NTksImV4cCI6MjA3MTEyNTU1OX0.CrEca8Hnnl5gkReY6dR4TKJez0tva7i2qopFDsMpjlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});